version: '3'

services:

  event-service-postgres:
    image: 'postgres'
    container_name: 'events-storage'
    volumes:
      - storage-data:/var/lib/postgresql/data
      - ./storage/:/var/lib/postgresql/scripts
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: events_storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  event-service-api:
    build: ./api
    container_name: 'events-api'
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: events-storage
      DB_PORT: 5432
      DB_NAME: events_storage
    ports:
      - 8080:8080
    links:
      - event-service-postgres

  event-service-ui:
    build: ./events-ui
    container_name: 'events-ui'
    environment:
      REACT_APP_API_URL: http://localhost:8080/api/v1
    ports:
      - 3000:3000
    links:
      - event-service-api


volumes:
  storage-data:
    external: true
